name: Build and Convert Kivy App to APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Convert Kivy App to APK
        run: |
          # Pull the Docker image from your registry
          docker pull registry.gitlab.com/my_user/my_repo:latest

          # Verify that the Dockerfile is in the current directory
          ls -l

          # Run the docker build command
          docker build --tag=buildozer .

      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: kivy-apk
          path: bin
