name: Build Android APK

on:
  push:
    branches:
      - main  # You can adjust the branch name here

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7  # Adjust the Python version if needed

      - name: Build with Buildozer
        run: |
          # Clone the Buildozer repository and build the Docker image
          git clone https://github.com/kivy/buildozer
          cd buildozer
          docker build --tag=buildozer .

          # Initialize your project and build the APK
          docker run --volume "$(pwd)":/home/user/hostcwd buildozer buildozer init
          # Make any necessary modifications to the buildozer.spec file here
          docker run --volume "$(pwd)":/home/user/hostcwd buildozer android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: my-android-app
          path: ./bin

